---
kind: List
apiVersion: v1
items:
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: glusterblock-provisioner-runner
    labels:
      glusterfs: block-provisioner-runner-clusterrole
      glusterblock: provisioner-runner-clusterrole
  rules:
    - apiGroups: [""]
      resources: ["persistentvolumes"]
      verbs: ["get", "list", "watch", "create", "delete"]
    - apiGroups: [""]
      resources: ["persistentvolumeclaims"]
      verbs: ["get", "list", "watch", "update"]
    - apiGroups: ["storage.k8s.io"]
      resources: ["storageclasses"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["list", "watch", "create", "update", "patch"]
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "create", "delete"]
    - apiGroups: [""]
      resources: ["routes"]
      verbs: ["get", "list"]
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: glusterblock-provisioner
    labels:
      glusterfs: block-provisioner-sa
      glusterblock: provisioner-sa
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: glusterblock-provisioner
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: glusterblock-provisioner-runner
  subjects:
  - kind: ServiceAccount
    name: glusterblock-provisioner
    namespace: ${NAMESPACE}
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: glusterblock-provisioner-deployment
    labels:
      glusterfs: block-provisioner-deployment
      glusterblock: provisioner-deployment
    annotations:
      description: Defines how to deploy the glusterblock provisioner pod.
  spec:
    replicas: 1
    template:
      metadata:
        name: glusterblock-provisioner
        labels:
          glusterfs: block-provisioner-pod
      spec:
        serviceAccountName: glusterblock-provisioner
        containers:
        - name: glusterblock-provisioner
          image: gluster/glusterblock-provisioner:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: PROVISIONER_NAME
            value: gluster.org/glusterblock
