- name: build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_eth1.ipv4.address is defined
  with_items: "{{ groups['all'] }}"

- name: disable selinux
  selinux: state=disabled

- name: disable of selinux - now
  command: setenforce 0
  ignore_errors: yes

- name: install centos and epel repos
  command: yum -y install centos-release-gluster epel-release
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 1

- name: setup kubernetes repo
  copy: src=kubernetes.repo owner=root group=root dest=/etc/yum.repos.d

- name: install base packages
  command: yum -y install {{ install_pkgs }}
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 1

- name: Ensure net.bridge.bridge-nf-call-iptables is set. See kubeadm
  copy: src=k8s.conf owner=root group=root dest=/etc/sysctl.d/k8s.conf

- name: enable kube services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - docker
    - kubelet

#- name: save iptables
#  command: service iptables save

- name: configure dm_snapshot module
  copy: src=dm_snapshot.conf owner=root group=root mode=644 dest=/etc/modules-load.d

- name: update kubernetes
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/{{ item }}
    dest: /usr/bin
    mode: 0755
  with_items:
    - kubelet
    - kubectl

- name: Ensure firewalld.service
  service: name=firewalld state=started enabled=yes

- name: firewall trust eth1
  firewalld: zone=trusted interface=eth1 permanent=true state=enabled immediate=true

- name: firewall trust weave
  firewalld: zone=trusted interface=weave permanent=true state=enabled immediate=true

- name: firewall trust 172.42.42.0/24
  firewalld: source=172.42.42.0/24 zone=trusted permanent=true state=enabled immediate=true

# 10.32.0.0/12 is the default pod CIDR for Weave Net
# you will need to update this if you are using a different
# network provider, or a different CIDR for whatever reason
- name: firewall trust weave net CIDR
  firewalld: source=10.32.0.0/12 zone=trusted permanent=true state=enabled immediate=true

- name: firewall trust port 10250
  firewalld: port=10250/tcp zone=trusted permanent=true state=enabled immediate=true

- name: firewall trust port 6443
  firewalld: port=6443/tcp zone=trusted permanent=true state=enabled immediate=true

- name: firewall trust port 9898
  firewalld: port=9898/tcp zone=trusted permanent=true state=enabled immediate=true
